// Generated by gencpp from file act_dp_service/get_action.msg
// DO NOT EDIT!


#ifndef ACT_DP_SERVICE_MESSAGE_GET_ACTION_H
#define ACT_DP_SERVICE_MESSAGE_GET_ACTION_H

#include <ros/service_traits.h>


#include <act_dp_service/get_actionRequest.h>
#include <act_dp_service/get_actionResponse.h>


namespace act_dp_service
{

struct get_action
{

typedef get_actionRequest Request;
typedef get_actionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct get_action
} // namespace act_dp_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::act_dp_service::get_action > {
  static const char* value()
  {
    return "158a528fc884a7668a43b64fd5398f56";
  }

  static const char* value(const ::act_dp_service::get_action&) { return value(); }
};

template<>
struct DataType< ::act_dp_service::get_action > {
  static const char* value()
  {
    return "act_dp_service/get_action";
  }

  static const char* value(const ::act_dp_service::get_action&) { return value(); }
};


// service_traits::MD5Sum< ::act_dp_service::get_actionRequest> should match
// service_traits::MD5Sum< ::act_dp_service::get_action >
template<>
struct MD5Sum< ::act_dp_service::get_actionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::act_dp_service::get_action >::value();
  }
  static const char* value(const ::act_dp_service::get_actionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::act_dp_service::get_actionRequest> should match
// service_traits::DataType< ::act_dp_service::get_action >
template<>
struct DataType< ::act_dp_service::get_actionRequest>
{
  static const char* value()
  {
    return DataType< ::act_dp_service::get_action >::value();
  }
  static const char* value(const ::act_dp_service::get_actionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::act_dp_service::get_actionResponse> should match
// service_traits::MD5Sum< ::act_dp_service::get_action >
template<>
struct MD5Sum< ::act_dp_service::get_actionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::act_dp_service::get_action >::value();
  }
  static const char* value(const ::act_dp_service::get_actionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::act_dp_service::get_actionResponse> should match
// service_traits::DataType< ::act_dp_service::get_action >
template<>
struct DataType< ::act_dp_service::get_actionResponse>
{
  static const char* value()
  {
    return DataType< ::act_dp_service::get_action >::value();
  }
  static const char* value(const ::act_dp_service::get_actionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ACT_DP_SERVICE_MESSAGE_GET_ACTION_H
