// Generated by gencpp from file act_dp_service/get_actionResponse.msg
// DO NOT EDIT!


#ifndef ACT_DP_SERVICE_MESSAGE_GET_ACTIONRESPONSE_H
#define ACT_DP_SERVICE_MESSAGE_GET_ACTIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float64MultiArray.h>

namespace act_dp_service
{
template <class ContainerAllocator>
struct get_actionResponse_
{
  typedef get_actionResponse_<ContainerAllocator> Type;

  get_actionResponse_()
    : actions()  {
    }
  get_actionResponse_(const ContainerAllocator& _alloc)
    : actions(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float64MultiArray_<ContainerAllocator>  _actions_type;
  _actions_type actions;





  typedef boost::shared_ptr< ::act_dp_service::get_actionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::act_dp_service::get_actionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct get_actionResponse_

typedef ::act_dp_service::get_actionResponse_<std::allocator<void> > get_actionResponse;

typedef boost::shared_ptr< ::act_dp_service::get_actionResponse > get_actionResponsePtr;
typedef boost::shared_ptr< ::act_dp_service::get_actionResponse const> get_actionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::act_dp_service::get_actionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::act_dp_service::get_actionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::act_dp_service::get_actionResponse_<ContainerAllocator1> & lhs, const ::act_dp_service::get_actionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.actions == rhs.actions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::act_dp_service::get_actionResponse_<ContainerAllocator1> & lhs, const ::act_dp_service::get_actionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace act_dp_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::act_dp_service::get_actionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::act_dp_service::get_actionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::act_dp_service::get_actionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::act_dp_service::get_actionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::act_dp_service::get_actionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::act_dp_service::get_actionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::act_dp_service::get_actionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a0770e10a9dd25aa1532dcce6ecc6c4d";
  }

  static const char* value(const ::act_dp_service::get_actionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa0770e10a9dd25aaULL;
  static const uint64_t static_value2 = 0x1532dcce6ecc6c4dULL;
};

template<class ContainerAllocator>
struct DataType< ::act_dp_service::get_actionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "act_dp_service/get_actionResponse";
  }

  static const char* value(const ::act_dp_service::get_actionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::act_dp_service::get_actionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 输出: 机器人关节角度（numpy 数组）\n"
"std_msgs/Float64MultiArray actions\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"float64[]         data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
;
  }

  static const char* value(const ::act_dp_service::get_actionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::act_dp_service::get_actionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.actions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct get_actionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::act_dp_service::get_actionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::act_dp_service::get_actionResponse_<ContainerAllocator>& v)
  {
    s << indent << "actions: ";
    s << std::endl;
    Printer< ::std_msgs::Float64MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.actions);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACT_DP_SERVICE_MESSAGE_GET_ACTIONRESPONSE_H
