// Generated by gencpp from file act_dp_service/RawData.msg
// DO NOT EDIT!


#ifndef ACT_DP_SERVICE_MESSAGE_RAWDATA_H
#define ACT_DP_SERVICE_MESSAGE_RAWDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float64MultiArray.h>
#include <std_msgs/Float64MultiArray.h>
#include <std_msgs/Float64MultiArray.h>
#include <std_msgs/Float64MultiArray.h>
#include <std_msgs/Float64.h>
#include <std_msgs/UInt8MultiArray.h>
#include <std_msgs/Bool.h>

namespace act_dp_service
{
template <class ContainerAllocator>
struct RawData_
{
  typedef RawData_<ContainerAllocator> Type;

  RawData_()
    : ee_pose()
    , joint_pos()
    , init_ee_pose()
    , init_joint_pos()
    , gripper_width()
    , rgb_data()
    , reset()  {
    }
  RawData_(const ContainerAllocator& _alloc)
    : ee_pose(_alloc)
    , joint_pos(_alloc)
    , init_ee_pose(_alloc)
    , init_joint_pos(_alloc)
    , gripper_width(_alloc)
    , rgb_data(_alloc)
    , reset(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float64MultiArray_<ContainerAllocator>  _ee_pose_type;
  _ee_pose_type ee_pose;

   typedef  ::std_msgs::Float64MultiArray_<ContainerAllocator>  _joint_pos_type;
  _joint_pos_type joint_pos;

   typedef  ::std_msgs::Float64MultiArray_<ContainerAllocator>  _init_ee_pose_type;
  _init_ee_pose_type init_ee_pose;

   typedef  ::std_msgs::Float64MultiArray_<ContainerAllocator>  _init_joint_pos_type;
  _init_joint_pos_type init_joint_pos;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _gripper_width_type;
  _gripper_width_type gripper_width;

   typedef  ::std_msgs::UInt8MultiArray_<ContainerAllocator>  _rgb_data_type;
  _rgb_data_type rgb_data;

   typedef  ::std_msgs::Bool_<ContainerAllocator>  _reset_type;
  _reset_type reset;





  typedef boost::shared_ptr< ::act_dp_service::RawData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::act_dp_service::RawData_<ContainerAllocator> const> ConstPtr;

}; // struct RawData_

typedef ::act_dp_service::RawData_<std::allocator<void> > RawData;

typedef boost::shared_ptr< ::act_dp_service::RawData > RawDataPtr;
typedef boost::shared_ptr< ::act_dp_service::RawData const> RawDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::act_dp_service::RawData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::act_dp_service::RawData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::act_dp_service::RawData_<ContainerAllocator1> & lhs, const ::act_dp_service::RawData_<ContainerAllocator2> & rhs)
{
  return lhs.ee_pose == rhs.ee_pose &&
    lhs.joint_pos == rhs.joint_pos &&
    lhs.init_ee_pose == rhs.init_ee_pose &&
    lhs.init_joint_pos == rhs.init_joint_pos &&
    lhs.gripper_width == rhs.gripper_width &&
    lhs.rgb_data == rhs.rgb_data &&
    lhs.reset == rhs.reset;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::act_dp_service::RawData_<ContainerAllocator1> & lhs, const ::act_dp_service::RawData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace act_dp_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::act_dp_service::RawData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::act_dp_service::RawData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::act_dp_service::RawData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::act_dp_service::RawData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::act_dp_service::RawData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::act_dp_service::RawData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::act_dp_service::RawData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a2490b5f4d8422f6e431911c53295728";
  }

  static const char* value(const ::act_dp_service::RawData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa2490b5f4d8422f6ULL;
  static const uint64_t static_value2 = 0xe431911c53295728ULL;
};

template<class ContainerAllocator>
struct DataType< ::act_dp_service::RawData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "act_dp_service/RawData";
  }

  static const char* value(const ::act_dp_service::RawData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::act_dp_service::RawData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float64MultiArray ee_pose     # 当前末端执行器 (End-Effector) 的位姿信息, 数据格式为一维数组: [位置 x, 位置 y, 位置 z, 朝向四元数 w, 朝向四元数 x, 朝向四元数 y, 朝向四元数 z]\n"
"std_msgs/Float64MultiArray joint_pos     # 关节角度，[joint1,joint2,...,joint7]\n"
"\n"
"std_msgs/Float64MultiArray init_ee_pose    # 初始末端执行器 (End-Effector) 的位姿信息\n"
"std_msgs/Float64MultiArray init_joint_pos    # 初始关节角度\n"
"\n"
"std_msgs/Float64 gripper_width           # 夹爪宽度\n"
"std_msgs/UInt8MultiArray rgb_data        # RGB 图像数据， (height x width x 3)\n"
"\n"
"std_msgs/Bool            reset           # 重置信号：True 表示请求系统重置或回到初始状态\n"
"================================================================================\n"
"MSG: std_msgs/Float64MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"float64[]         data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayLayout\n"
"# The multiarray declares a generic multi-dimensional array of a\n"
"# particular data type.  Dimensions are ordered from outer most\n"
"# to inner most.\n"
"\n"
"MultiArrayDimension[] dim # Array of dimension properties\n"
"uint32 data_offset        # padding elements at front of data\n"
"\n"
"# Accessors should ALWAYS be written in terms of dimension stride\n"
"# and specified outer-most dimension first.\n"
"# \n"
"# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n"
"#\n"
"# A standard, 3-channel 640x480 image with interleaved color channels\n"
"# would be specified as:\n"
"#\n"
"# dim[0].label  = \"height\"\n"
"# dim[0].size   = 480\n"
"# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n"
"# dim[1].label  = \"width\"\n"
"# dim[1].size   = 640\n"
"# dim[1].stride = 3*640 = 1920\n"
"# dim[2].label  = \"channel\"\n"
"# dim[2].size   = 3\n"
"# dim[2].stride = 3\n"
"#\n"
"# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/MultiArrayDimension\n"
"string label   # label of given dimension\n"
"uint32 size    # size of given dimension (in type units)\n"
"uint32 stride  # stride of given dimension\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
"================================================================================\n"
"MSG: std_msgs/UInt8MultiArray\n"
"# Please look at the MultiArrayLayout message definition for\n"
"# documentation on all multiarrays.\n"
"\n"
"MultiArrayLayout  layout        # specification of data layout\n"
"uint8[]           data          # array of data\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Bool\n"
"bool data\n"
;
  }

  static const char* value(const ::act_dp_service::RawData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::act_dp_service::RawData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ee_pose);
      stream.next(m.joint_pos);
      stream.next(m.init_ee_pose);
      stream.next(m.init_joint_pos);
      stream.next(m.gripper_width);
      stream.next(m.rgb_data);
      stream.next(m.reset);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RawData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::act_dp_service::RawData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::act_dp_service::RawData_<ContainerAllocator>& v)
  {
    s << indent << "ee_pose: ";
    s << std::endl;
    Printer< ::std_msgs::Float64MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.ee_pose);
    s << indent << "joint_pos: ";
    s << std::endl;
    Printer< ::std_msgs::Float64MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.joint_pos);
    s << indent << "init_ee_pose: ";
    s << std::endl;
    Printer< ::std_msgs::Float64MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.init_ee_pose);
    s << indent << "init_joint_pos: ";
    s << std::endl;
    Printer< ::std_msgs::Float64MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.init_joint_pos);
    s << indent << "gripper_width: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.gripper_width);
    s << indent << "rgb_data: ";
    s << std::endl;
    Printer< ::std_msgs::UInt8MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.rgb_data);
    s << indent << "reset: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.reset);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACT_DP_SERVICE_MESSAGE_RAWDATA_H
