# config.yaml
scenary:
  _target_: src.scenary.base.BaseScenary
  usd_file_path: "./assets/realman_env_2.usd"

controller:
  _target_: src.controller.base.ROSServiceController
  ros_service_name: sensor_processing
  
sensor:
  _target_: src.sensor.base.Camera
  camera_prim_path: /World/GEN72/panda_hand_01/owl/camera
  camera_freq: 20 
  resolution: [640,360]

robot:
  _target_: src.robots.base.BaseRobot
  robot_prim_path: /World/GEN72
  joints_name: [
     joint1,joint2,joint3,joint4,joint5,joint6,joint7,panda_finger_joint1
  ]
  ee_prim_path: /World/GEN72/panda_hand_01/tool_center
  gripper_joint_name: panda_finger_joint1

dataset:
  _target_: src.dataset.base.ACTDataset
  dataset_dir: ./datasets/grasp_corn_real_pan
  episode_nums: 1
  is_degree: true

task:
  _target_: src.task.base.BaseTask
  replay_horizon: 0  # -1 代表 replay 所有数据
  replay_trajectory_index: 0
  # eval_open_loop_loss: true # 在 replay 的过程中，是否需要评估开环的Loss


sensor_list: []    # 可以加入更多 sensor 配置  