# config.yaml
scenary:
  _target_: src.scenary.base.StackCubeScenary
  usd_file_path: "./assets/data_collect.usd"
  src_cube_cfg: {
      name: cube_red,
      position: [ 0.31164142, -0.11513411,  0.18      ],
      # orientation: [],
      prim_path: /World/Cube,
      scale: [0.05, 0.05, 0.05],
      size: 1.0,
      color: [1, 0, 0]
  }
  target_cube_cfg: {
      name: cube_blue,
      position: [0.48913025, 0.18421585, 0.18      ],
      # orientation: [],
      prim_path: /World/Cube2,
      scale: [0.05, 0.05, 0.05],
      size: 1.0,
      color: [0, 0, 1]
  }

controller:
  _target_: src.controller.base.RandomController
  dof_num: 8
  low: -1.0 
  high: 1
  
sensor:
  _target_: src.sensor.base.Camera
  camera_prim_path: /World/franka/panda_hand/owl/camera
  camera_freq: 10 
  resolution: [1280,720]

robot:
  _target_: src.robots.base.BaseRobot
  robot_prim_path: /World/franka
  joints_name: [
     panda_joint1,panda_joint2,panda_joint3,panda_joint4,panda_joint5,panda_joint6,panda_joint7,panda_finger_joint1
  ]

task:
  _target_: src.task.base.BaseTask

sensor_list: []    # 可以加入更多 sensor 配置  