frequencies:
  control: 20
  camera: 20
  sim: 60


task:
    _target_: src.task.base.BaseTask
    frequencies: ${frequencies}
    scenary:
        _target_: src.scenary.stack_cube.StackCubeScenary 
        usd_file_path: "./assets/franka_transfer_cube.usd"
        src_cube_cfg: {
            name: cube_red,  
            position: [ 0.148716 , 0.000000, 0.120000],
            prim_path: /World/Cube,
            scale: [0.05, 0.05, 0.05],
            size: 1.0,
            color: [1, 0, 0]
        }

    env_sensors:
        camera_rgb_overhead:
            _target_: src.sensor.camera.Camera
            camera_prim_path: /World/overhead_camera
            camera_freq: ${frequencies.camera} 
            resolution: [640,480]
        camera_rgb_front:
            _target_: src.sensor.camera.Camera
            camera_prim_path: /World/front_camera
            camera_freq: ${frequencies.camera} 
            resolution: [640,480]
    robot:
        _target_: src.robots.Bimanual.BimanualRobot
        left_arm: 
            _target_: src.robots.base.BaseRobot
            robot_prim_path: /World/franka2
            joints_name: [
                panda_joint1,panda_joint2,panda_joint3,panda_joint4,panda_joint5,panda_joint6,panda_joint7,panda_finger_joint1
            ]
            ee_prim_path: /World/franka2/panda_hand/tool_center
            gripper_joint_name: panda_finger_joint1
            sensors:
                camera_rgb_left_wrist:
                    _target_: src.sensor.camera.Camera
                    camera_prim_path: /World/franka2/panda_hand/owl/camera
                    camera_freq: ${frequencies.camera} 
                    resolution: [640,480]

        right_arm: 
            _target_: src.robots.base.BaseRobot
            robot_prim_path: /World/franka1
            joints_name: [
                panda_joint1,panda_joint2,panda_joint3,panda_joint4,panda_joint5,panda_joint6,panda_joint7,panda_finger_joint1
            ]
            ee_prim_path: /World/franka1/panda_hand/tool_center
            gripper_joint_name: panda_finger_joint1
            sensors:
                camera_rgb_right_wrist:
                    _target_: src.sensor.camera.Camera
                    camera_prim_path: /World/franka1/panda_hand/owl/camera
                    camera_freq: ${frequencies.camera} 
                    resolution: [640,480]

    dataset:
        _target_: src.dataset.act_dataset.ACTDataset
        dataset_dir: ./datasets/stack_cube_act_sim
        episode_nums: 1

    replay_horizon: -1
    replay_trajectory_index: 0
            